---
title: "ssGSEA Neuroendocrine Scores, Heatmaps, etc."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#### R/Data Analysis Background
+ [ModernDive](https://moderndive.com/index.html)
+ [R for Data Science](https://r4ds.had.co.nz/)

#### R Packages to install (if not already installed)
+ [tidyverse](https://www.tidyverse.org/)
+ [ggrepel](https://cran.r-project.org/web/packages/ggrepel/index.html)
+ [GSVA](https://bioconductor.org/packages/release/bioc/html/GSVA.html)
+ [ComplexHeatmap](https://jokergoo.github.io/ComplexHeatmap-reference/book/)
+ [circlize](https://cran.r-project.org/web/packages/circlize/index.html)
+ [writexl](https://cran.r-project.org/web/packages/writexl/index.html)

```{r startup, message=FALSE, warning=FALSE}
library(tidyverse)

# Read Gene Set
gsets <- readRDS("Genesets.rds")

# Read gene expression table
exp_tbl <- readxl::read_xlsx("data/atri_study_rna.xlsx")

```


```{r helper_functions}

# Compute a table of ssGSEA (Single Sample Gene Set Enrichment Analysis)
# scores for a list of gene sets.
# PARAMETERS:
# X: A gene expression data table with gene names in the first column,
#    followed by sample-specific gene expression columns.
#
# gene_sets: A named list object with character vectors indicating 
#            gene sets for which ssGSEA scores are to be computed.

get_ssgsea_table <- function(X, gene_sets) {
  if (is.data.frame(X)) {
    X <- X %>%
      tibble::column_to_rownames(colnames(.)[[1]]) %>%
      as.data.frame() %>%
      as.matrix()
  }
  stopifnot(!any(duplicated(rownames(X))), is.numeric(X))
  
  # Remove genes w/constant expression
  #gene_sdev <- apply(X, MARGIN = 1, FUN = stats::sd)
  #X <- X[gene_sdev != 0, , drop = FALSE]
  
  set.seed(1)
  ssgsea_tab <- GSVA::gsva(expr = X, gset.idx.list = gene_sets,
                           method = 'ssgsea', kcdf = "Gaussian",
                           verbose=FALSE) %>%
    t() %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "sample_id") %>%
    tibble::as_tibble()

  return(ssgsea_tab)
}

```


# Compute Various ssGSEA-Based Neuroendocrine Scores
```{r compute_ssgsea_scores}
# Construct list object with gene sets for which ssGSEA scores will be computed
ne_scores_tbl <- get_ssgsea_table(X = exp_tbl, gene_sets = gsets)

# using the Gazdar NE and non-NE gene sets. Adding a column with this below:

ne_scores_tbl <- ne_scores_tbl %>%
  dplyr::mutate(
    NE50  = SCLC_Neuroendocrine - SCLC_Non_Neuroendocrine
  )

writexl::write_xlsx(ne_scores_tbl, path = "tables/ne_scores_tbl.xlsx")
```